### ISSUE TITLE
Setup GH Actions

### ISSUE THREAD

**Issue by slactjohnson** [pcdshub/btms-ui#8]
## Expected Behavior
The repo has GH actions that actually run

## Current Behavior
This repo got set up with required GH actions, but they aren't set up to run for some reason. This is preventing PRs from being merged. 

## Possible Solution
Configure the GH actions to run.

**Comment by tangkong** [comment]
We can turn off required checks while we wait for these to get set up, if you like

**Comment by slactjohnson** [comment]
One day I hope to be as wise and powerful as admin people... 

It looks straightforward, hopefully I can get it done quickly today.
